version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./webapp/src:/src
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

  redis:
    image: redis
    restart: always

  worker:
    restart: always
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    volumes:
      - ./cats:/app/src/cats
    command: ['celery', '--workdir=/src', '-A', 'project', 'worker']